architecture:container:
  - changed-files:
      - any-glob-to-any-file:
          - apps/cores/**/*
architecture:serverless:
  - changed-files:
      - any-glob-to-any-file:
          - apps/**/bff/**/*
framework:react:
  - changed-files:
      - any-glob-to-any-file:
          - apps/users/client/extension/**/*
framework:commander:
  - changed-files:
      - any-glob-to-any-file:
          - apps/**/client/cli/**/*
framework:hono:
  - changed-files:
      - any-glob-to-any-file:
          - apps/**/bff/**/*
framework:nestjs:
  - changed-files:
      - any-glob-to-any-file:
          - apps/cores/**/*
tool:github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**/*
tool:biome:
  - changed-files:
      - any-glob-to-any-file:
          - tools/biome/**/*
tool:github-labels:
  - changed-files:
      - any-glob-to-any-file:
          - tools/github/labels/**/*
          - .github/labeler.yml
tool:typescript:
  - changed-files:
      - any-glob-to-any-file:
          - tools/typescript/**/*
tool:vitest:
  - changed-files:
      - any-glob-to-any-file:
          - tools/vitest/**/*
          - '**/vitest.config.*'
doc:readme:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - '**/README.md'
doc:architectures:
  - changed-files:
      - any-glob-to-any-file:
          - docs/architectures.md
doc:requirements:
  - changed-files:
      - any-glob-to-any-file:
          - docs/requirements.md
experience:cd:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**/*-deploy.{yaml,yml}
experience:ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**/*
experience:develop:
  - changed-files:
      - any-glob-to-any-file:
          - tsconfig.json
          - .npmrc
          - .gitignore
          - package.json
          - .husky/**/*
          - .vscode/**/*
experience:docker:
  - changed-files:
      - any-glob-to-any-file:
          - docker-compose.{yaml,yml}
          - '**/docker-compose.{yaml,yml}'
          - Dockerfile
          - '**/Dockerfile'
role:bff:
  - changed-files:
      - any-glob-to-any-file:
          - apps/**/bff/**/*
role:client:
  - changed-files:
      - any-glob-to-any-file:
          - apps/client/**/*
role:service:
  - changed-files:
      - any-glob-to-any-file:
          - apps/cores/**/*
