architecture:container:
  - changed-files:
      - apps/cores/**/*
architecture:serverless:
  - changed-files:
      - apps/**/bff/**/*
framework:react:
  - changed-files:
      - apps/users/client/extension/**/*
framework:commander:
  - changed-files:
      - apps/**/client/cli/**/*
framework:hono:
  - changed-files:
      - apps/**/bff/**/*
framework:nestjs:
  - changed-files:
      - apps/cores/**/*
tool:biome:
  - changed-files:
      - tools/biome/**/*
tool:github-actions:
  - changed-files:
      - .github/workflows/**/*
tool:github-labels:
  - changed-files:
      - .github/labeler.yml
tool:typescript:
  - changed-files:
      - "**/*.ts"
      - "**/*.tsx"
tool:vitest:
  - changed-files:
      - "**/vitest.config.*"
      - "**/*.test.ts"
      - "**/*.spec.ts"
doc:readme:
  - changed-files:
      - README.md
doc:architectures:
  - changed-files:
      - docs/architectures.md
doc:requirements:
  - changed-files:
      - docs/requirements.md
experience:cd:
  - changed-files:
      - .github/workflows/**/*-deploy.{yaml,yml}
experience:ci:
  - changed-files:
      - .github/workflows/**/*
experience:develop:
  - changed-files:
      - tsconfig.json
      - .npmrc
      - .gitignore
      - package.json
      - .husky/**/*
      - .vscode/**/*
experience:docker:
  - changed-files:
      - docker-compose.{yaml,yml}
      - "**/docker-compose.{yaml,yml}"
      - Dockerfile
      - "**/Dockerfile"
role:bff:
  - changed-files:
      - apps/**/bff/**/*
role:client:
  - changed-files:
      - apps/client/**/*
role:service:
  - changed-files:
      - apps/cores/**/*
