packages:
  - tools/*
  - packages/*
  - apps/cores/**
  - apps/users/**
  - apps/managers/*

catalog:
  '@vitest/coverage-v8': '^2.1.1'
  '@biomejs/biome': ^1.9.4
  unplugin-swc: ^1.5.1
  vitest: ^2.1.1
  husky: ^9.1.6
  '@tsconfig/strictest': ^2.0.5
  '@types/node': ^22.7.3
  typescript: ^5.6.2
  tsx: ^4.19.1
